repos:
  - repo: https://github.com/AleksanderWWW/aircheck
    rev: 0.1.0rc0  # Use the latest release tag
    hooks:
      - id: aircheck
        name: Validate Airflow DAGs
        entry: aircheck
        language: python
        types: [python]
